language: node_js
node_js:
  - stable
env:
  - CI=true
  - CXX=g++-5
install:
  - yarn
script:
  - yarn build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: master

