language: node_js
node_js:
  - stable
cache: yarn
env:
  - CI=true
script:
  - yarn build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: storybook

